repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
            args: ['--maxkb=600']
          - id: end-of-file-fixer
          - id: detect-private-key
          - id: debug-statements
          - id: check-case-conflict
          - id: check-ast

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            args: [--exclude=__init__.py, --max-line-length=120]

    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
          - id: reorder-python-imports

    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.0.2
      hooks:
          - id: autopep8
