services:
    smw-db:
        image: postgres:15.2
        environment:
            - POSTGRES_DB=save_my_wallet
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
        ports:
            - "5432:5432"
        volumes:
            - "./db:/var/lib/postgresql/data"
    
    smw-db-test:
        image: postgres:15.2
        environment:
            - POSTGRES_DB=smw_db_test
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
        ports:
            - "54322:5432"
