"""Change on field updated and created at

Revision ID: 1d05dbde5866
Revises: 2145cc6ccdd7
Create Date: 2023-04-16 02:05:28.779835

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d05dbde5866'
down_revision = '2145cc6ccdd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'creation_date')
    op.drop_column('users', 'last_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'last_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('creation_date',
                  postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
