"""create accounts and credit_cards tables

Revision ID: 6eae182efa3a
Revises: d5be06e1928d
Create Date: 2026-06-19 20:54:52.264068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eae182efa3a'
down_revision: Union[str, Sequence[str], None] = 'd5be06e1928d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('main_credit_card_id', sa.UUID(), nullable=True),
    sa.Column('closing_day', sa.SmallInteger(), nullable=False),
    sa.Column('due_day', sa.SmallInteger(), nullable=False),
    sa.Column('limit', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('financing_limit', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['main_credit_card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_cards')
    op.drop_table('accounts')
    # ### end Alembic commands ###
