"""create expenses and payments tables

Revision ID: f199f3a6040f
Revises: 6eae182efa3a
Create Date: 2026-06-19 21:15:29.635703

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f199f3a6040f"
down_revision: str | Sequence[str] | None = "6eae182efa3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column("acquired_at", sa.Date(), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column("expense_type", sa.String(length=50), nullable=False),
        sa.Column("total_installments", sa.SmallInteger(), nullable=True),
        sa.Column("first_payment_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("amount > 0", name="chk_expense_amount_positive"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["movement_categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column("no_installment", sa.SmallInteger(), nullable=False),
        sa.Column("period_month", sa.SmallInteger(), nullable=False),
        sa.Column("period_year", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("is_last_payment", sa.Boolean(), nullable=False),
        sa.Column("credit_card_code", sa.String(length=100), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.CheckConstraint("amount > 0", name="chk_payment_amount_positive"),
        sa.CheckConstraint("period_month BETWEEN 1 AND 12", name="chk_payment_period_month"),
        sa.ForeignKeyConstraint(["expense_id"], ["expenses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("expense_id", "period_year", "period_month", name="uq_expense_period"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("expenses")
    # ### end Alembic commands ###
